[package]
name = "jb-shell"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk4 = "0.10"
gtk4-layer-shell = "0.7"
glib = "0.21"
gdk4 = "0.10"
gio = "0.21"
chrono = "0.4"
battery = "0.7"
hyprland = "0.4.0-beta.3"
relm4 = "0.10"
